baseURL = "https://blog.uzzzzz.xyz/"
languageCode = "zh-cn"
title = "My Blog"
theme = "hugo-theme-air"
publishdir = "docs"
ignoreFiles = [ "themes/" ]

[params]
  author = "uzzzzz"
  description = "个人博客"
  share = false