baseURL = "https://blog.uzzzzz.xyz/"
languageCode = "zh-cn"
title = "My Blog"
theme = "hugo-theme-air"
publishdir = "docs"
ignoreFiles = [ "themes/" ]

[params]
  author = "uzzzzz"
  description = "个人博客"
  share = false
  authorwebsite = "https://blog.uzzzzz.xyz/"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "UUZZzga"
  twitterName = ""
  hideHUGOSupport = false